server.port=80

datasource.main.jdbc-url=jdbc:postgresql://finmates.com:5432/main
datasource.main.username=${DB_USERNAME:user}
datasource.main.password=${DB_PASSWORD:Int6859351!}
datasource.main.driver-class-name=org.postgresql.Driver

datasource.crypto.jdbc-url=jdbc:postgresql://finmates.com:5432/crypto
datasource.crypto.username=${DB_USERNAME:user}
datasource.crypto.password=${DB_PASSWORD:Int6859351!}
datasource.crypto.driver-class-name=org.postgresql.Driver

datasource.aggregator.jdbc-url=jdbc:postgresql://postgres:5432/crypto_aggregator
datasource.aggregator.username=${DB_USERNAME:user}
datasource.aggregator.password=${DB_PASSWORD:Int6859351!}
datasource.aggregator.driver-class-name=org.postgresql.Driver

#keycloak
keycloak.realm=finmates
keycloak.auth-server-url=https://auth.finmates.com
spring.security.oauth2.resourceserver.jwt.issuer-uri=${keycloak.auth-server-url}/realms/${keycloak.realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD}

aggregator.url=http://fm-crypto-aggregator:8088
