server.port=80

datasource.main.url=jdbc:postgresql://postgres-service.dev.svc.cluster.local:5432/finmates
datasource.crypto.url=jdbc:postgresql://postgres-service.dev.svc.cluster.local:5432/crypto

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak-service.dev.svc.cluster.local:8080/realms/finmates
