server.port=80

datasource.main.jdbc-url=jdbc:postgresql://postgres-service.dev.svc.cluster.local:5432/finmates
datasource.main.username=${DB_USERNAME:postgres}
datasource.main.password=${DB_PASSWORD:postgres}
datasource.main.driver-class-name=org.postgresql.Driver

datasource.crypto.jdbc-url=jdbc:postgresql://postgres-service.dev.svc.cluster.local:5432/crypto
datasource.crypto.username=${DB_USERNAME:postgres}
datasource.crypto.password=${DB_PASSWORD:postgres}
datasource.crypto.driver-class-name=org.postgresql.Driver

datasource.aggregator.jdbc-url=jdbc:postgresql://postgres-service.dev.svc.cluster.local:5432/crypto_aggregator
datasource.aggregator.username=${DB_USERNAME:postgres}
datasource.aggregator.password=${DB_PASSWORD:postgres}
datasource.aggregator.driver-class-name=org.postgresql.Driver

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak-service.dev.svc.cluster.local:8080/realms/finmates

keycloak.auth-server-url=http://keycloak-service.dev.svc.cluster.local:8080
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD}

aggregator.url=http://fm-crypto-aggregator-service.dev.svc.cluster.local:8088
